Name:           ros-kinetic-pcl-ros
Version:        1.4.0
Release:        0
Summary:        ROS pcl-ros package
Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/pcl_ros
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
Patch0:	        pcl-version-definition.patch 	
BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel => 3.0.0
BuildRequires:  pcl, pcl-devel

%description
CMake lint commands for ROS packages. The lint commands perform static checking
of Python or C++ source code for errors and standards compliance.

%prep
%setup -q
cp %{SOURCE1001} .
%patch0 -p1 -b .definition

%build
pushd pcl_ros
%{__ros_setup}
%{__ros_build}
popd

%install
pushd pcl_ros
%{__ros_setup}
%{__ros_install}
popd

%files -f pcl_ros/build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)
%{__ros_install_path}/lib/python2.7/site-packages/*

%changelog
* Mon Oct 30 2017 Geunsik Lim <geunsik.lim@samsung.com> - 1.4.0
- spec file is generated by Geunsik Lim

